### ISSUE TITLE
Plugin script is not found/missing

### ISSUE THREAD

**Issue by dsinni** [donmccurdy/aframe-inspector-plugin-recast#10]
The plugin script below is resulting in `Cannot GET /aframe-inspector-plugin-recast.js`

https://recast-api.donmccurdy.com/aframe-inspector-plugin-recast.js

**Comment by donmccurdy** [comment]
Had a broken deploy; should be fixed now. Testing against 0.8.2 and the inspector version it includes, but I think this should be OK for the latest inspector build too (if 0.8.2 isn't using it yet anyway).

**Comment by dsinni** [comment]
Okay, looking good as far as I can tell. Thanks, Don!
