### ISSUE TITLE
Plugin panel remains after exiting inspector

### ISSUE THREAD

**Issue by dsinni** [donmccurdy/aframe-inspector-plugin-recast#11]
Me again!

Just a heads-up that the Recast plugin panel remains displayed after exiting the inspector:

![image](https://user-images.githubusercontent.com/4733018/51493425-5675e900-1d83-11e9-8068-d62f9ea5573d.png)

I'm seeing this in both Firefox and Chrome on Windows 10.

**Comment by donmccurdy** [comment]
Testing on A-Frame 0.8.2 and 0.9.0 I can't reproduce this ... do you still see the problem, and if so could you share a demo?

**Comment by dsinni** [comment]
This looks like this has been resolved, either on this end or possibly within the inspector itself.

Perhaps a happy accident?

Either way, LGTM, so I'll close this. Thanks!
