### ISSUE TITLE
Export failing for basic scene in Chrome 71

### ISSUE THREAD

**Issue by EricEisaman** [donmccurdy/aframe-inspector-plugin-recast#12]
Here is the error.
```
aframe-inspector.min.js:25 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C (aframe-inspector.min.js:25)
    at k (aframe-inspector.min.js:25)
    at S (aframe-inspector.min.js:25)
    at A (aframe-inspector.min.js:25)
    at aframe-inspector.min.js:25
    at THREE.GLTFExporter.parse (aframe-inspector.min.js:25)
    at RecastPlugin.exportGLTF (aframe-inspector-plugin-recast.js:9280)
    at HTMLButtonElement.exportBtnEl.addEventListener (aframe-inspector-plugin-recast.js:9115)
```

[Here](https://www.youtube.com/watch?v=rfLd-L04PGk) is a video illustrating the issue.

**Comment by EricEisaman** [comment]
![screen shot 2019-02-03 at 5 59 52 am](https://user-images.githubusercontent.com/6116865/52175944-b011e680-2779-11e9-9638-51962af723e7.png)

**Comment by EricEisaman** [comment]
The navmesh is obviously present and functioning properly within the page.  Is the actual mesh being stored somewhere other than within the navmesh element?

**Comment by EricEisaman** [comment]
The same failed export happens in Safari 11.1.

**Comment by EricEisaman** [comment]
Once I made a simple example static web page project it worked fine.  There was something about the Node multiplayer server example I used that seemed to have contributed to the issue.

**Comment by donmccurdy** [comment]
Hm, glad you got it working! I'm not sure what would have broken it but if you are able to reproduce the issue later feel free to reopen this.

**Comment by Leostorm3** [comment]
I am actually running into the exact same issue was there any update on this

**Comment by donmccurdy** [comment]
I can't reproduce this issue – you'll need to share information (ideally a demo) for me to help. It's very probably something specific in the scene you're trying to work on.
