### ISSUE TITLE
wasd-controls conflict

### ISSUE THREAD

**Issue by da4throux** [donmccurdy/aframe-inspector-plugin-recast#20]
I do not understand why, but when explicitly adding the wasd-controls controler to the camera rig, then the nav mesh is not working anymore. If remove the component, then it work perfectly.

`
<!doctype html>
<html>
<head>
	<title>Navigation Meshes</title>
	<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
	<script src="//cdn.rawgit.com/donmccurdy/aframe-extras/v6.1.0/dist/aframe-extras.min.js"></script>
	<script src="https://recast-api.donmccurdy.com/aframe-inspector-plugin-recast.js"></script>
</head>

<body>
	<a-scene background="color: #FFFFFF" inspector-plugin-recast>
		
		<a-assets>
			<a-asset-item id="my-nav-mesh" src="navmesh.gltf"></a-asset-item>
		</a-assets>
		
		
		<a-entity movement-controls="speed: 0.15; constrainToNavMesh: true" position="0 0 2">
			
			<a-entity wasd-controls camera position="0 1.6 0"
					  look-controls="pointerLockEnabled: true">
				<a-cursor></a-cursor>
			</a-entity>
		</a-entity>
		
		
		<a-plane color="#333333" shader="flat" rotation="-90 0 0" scale="8 6 1">
		</a-plane>
		
		<a-entity gltf-model="#my-nav-mesh" nav-mesh position="0 -0.1 0" visible="true">
		</a-entity>
	</a-scene>
</body>
</html>
`

**Comment by da4throux** [comment]
Hmmm. it's probably not a relevant issue, as 'wasd-control' is redundant with 'movement-controls' ... I'm such a noob :D

**Comment by donmccurdy** [comment]
Right, `wasd-controls` doesn't know anything about the nav-mesh so it'll have trouble there. `movement-controls` should do the trick. :)
