### ISSUE TITLE
Glitches won't work

### ISSUE THREAD

**Issue by dirkk0** [donmccurdy/aframe-inspector-plugin-recast#5]
Hi,

  I came from this thread:
https://github.com/donmccurdy/aframe-extras/issues/225#issuecomment-385849705

and tried the examples (like https://cherry-teacher.glitch.me/); they all gave me an
```Cannot read property 'groups' of undefined```error once I hit a WASD key.

Thanks,
  Dirk

**Comment by donmccurdy** [comment]
Mainly, you can't walk around with `constrainToNavMesh: true` before creating a navmesh. Typically you would create the navmesh, export it, and then import it directly to your scene. But yeah ideally the scene shouldn't crash here and should let you test the navmesh nicely... :)

**Comment by dirkk0** [comment]
Sorry - my bad, it seems I missed a lot.
From your blog post it was 'create a  NavMesh in Blender', import it and you are ready to go.

Now I see that you need to enter the inspector (which I don't use much, generally), hit build, and *then* you are ready to go.
I guess I would prefer a (semi?-)automatic build when I load the file.

**Comment by donmccurdy** [comment]
The idea is that you can use the inspector plugin while authoring a scene — set up obstacles and models however you want — then build the navmesh and export it to a `.gltf` file. Once you've done that, you import the navmesh with `<a-entity gltf-model="navmesh.gltf" nav-mesh/>` as you'd do with a navmesh created in Blender.

For the finished scene, the plugin should not be included at all. You wouldn't want to build a navmesh every time a user visits the scene as that (1) takes a while and (2) requires uploading the entire scene to a server for processing.

This just lets the Inspector replace Blender for building the navigation mesh, as a one-time step.

**Comment by donmccurdy** [comment]
The issue about movement throwing errors until a navmesh is created should be fixed on latest aframe-extras. I'll document the rest of this when the plugin is further along.
