### ISSUE TITLE
"Cannot read property 'id' of undefined" error

### ISSUE THREAD

**Issue by dirkk0** [donmccurdy/aframe-inspector-plugin-recast#8]
Hi,

  first of all, let me mention that my tests of interior like Blender models were all successful, thanks to your work!

My attempts with a somewhat larger terrain worked out, too, but occasionally throw this error on a specific part of the model:

    aframe-extras.min.js:1 Uncaught TypeError: Cannot read property 'id' of undefined
        at e.clampStep (aframe-extras.min.js:1)
        at o.clampStep (aframe-extras.min.js:1)
    ...
    at y (aframe8.2.min.js:100)

Any idea why that is?
I can supply the Blender file plus export, if needed.

Thanks, Dirk

**Comment by donmccurdy** [comment]
Hard to say — if you can provide the model or a demo that would help thanks!

**Comment by dirkk0** [comment]
thanks!

here you go:
http://curious-electric.com/_del/t5.zip

**Comment by donmccurdy** [comment]
Can't seem to reproduce this just walking around, any particular version of A-Frame Extras? If you could get a line number on the error from the un-minified version of Extras that might help too.

**Comment by donmccurdy** [comment]
Closing for now, but glad to debug this if I can find a way to reproduce it. :)

**Comment by dirkk0** [comment]
yes, sorry for the delay and thanks for looking into this!
As soon as I find time to check again, I'll reopen.
