### ISSUE TITLE
`inspector-plugin-recast` doesn't work with current A-Frame inspector

### ISSUE THREAD

**Issue by dsinni** [donmccurdy/aframe-inspector-plugin-recast#9]
I noticed today that `inspector-plugin-recast` no longer works, likely due to the A-Frame Inspector update.

The interface is present in the inspector, but when I hit "Build", I get the following error:

![image](https://user-images.githubusercontent.com/4733018/51414541-da8c5e80-1b40-11e9-93d7-60647d31fe56.png)

Nothing is built or able to be exported.

This tool is awesome and much needed, especially considering the direction Blender is taking, so I look forward to being able to use it again with the current inspector.

Thanks for all you do.

**Comment by donmccurdy** [comment]
Hm thanks, what version of aframe are you using? when you say current inspector, is that what aframe does by itself, or are you overriding the inspector version?

**Comment by dsinni** [comment]
I tried in both A-Frame `0.8.2` and the latest `master`: `A-Frame Version: 0.8.2 (Date 2019-01-15, Commit #69e08c0)`

I'm not overriding the inspector version; it's just the one included with A-Frame. IIRC, the inspector was recently updated even in `0.8.2`.

**Comment by donmccurdy** [comment]
Should be fixed now, thanks!

**Comment by dsinni** [comment]
Thanks for the timely response, @donmccurdy.

I can't seem to get the plugin interface to display, however. I tried in both A-Frame `0.8.2` and `master`, both of which appear to be using https://unpkg.com/aframe-inspector@0.8.x/dist/aframe-inspector.min.js, which is currently pointing to Inspector `0.8.16` if that is at all helpful.

Maybe I'm just missing something. Is there a shortcut needed now?

**Comment by dsinni** [comment]
The above was resolved as well. Thanks!
